verify and show version number

diff --git a/.github/workflows/docker_image.yml b/.github/workflows/docker_image.yml
--- a/.github/workflows/docker_image.yml
+++ b/.github/workflows/docker_image.yml
@@ -12,7 +12,36 @@ on:
       - main
 
 jobs:
+  version:
+    name: Detect version
+    runs-on: ubuntu-latest
+    outputs:
+      tag: ${{ steps.version.outputs.tag }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Install yq
+        run: |
+          sudo apt-get install -y yq
+      - id: version
+        run: |
+          TAG=$(yq e '.slogan | sub("^v", "")' web/sites/default/files/sync/system.site.yml)
+          echo "${TAG}"
+          echo "tag=${TAG}" >> $GITHUB_OUTPUT
+      - name: Check git tag
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          GIT_TAG="${GITHUB_REF#refs/tags/}"
+          EXPECTED_TAG="v${{ steps.version.outputs.tag }}"
+          if [[ "${GIT_TAG}" != "${EXPECTED_TAG}" ]]; then
+            echo "Error: Git tag (${GIT_TAG}) does not match version from system.site.yml (v${{ steps.version.outputs.tag }})"
+            exit 1
+          fi
+
   build-artifacts:
+    needs: [ version ]
+
     strategy:
       matrix:
         arch: [amd64, arm64]
